go-router/main/default/objects/Go_Router__mdt/Go_Router__mdt.object-meta.xml
<CustomObject>
    <description>Definitions of all routes exposed to the /apex/go endpoint.</description>
    <label>Go Router</label>
    <pluralLabel>Go Routers</pluralLabel>
</CustomObject>

go-router/main/default/objects/Go_Router__mdt/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>The route exposed for this GoRouter (i.e. /apex/go/key =&gt; activates this router).</description>
    <inlineHelpText>The route exposed for this GoRouter (i.e. /apex/go/key =&gt; activates this router).</inlineHelpText>
    <label>Key</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

go-router/main/default/classes/GoRouterTestUtility.cls
/**
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @group GoRouter
 * @description Utility methods that can be integrated into the test suite of
 * an instance.
 */
@IsTest
private with sharing class GoRouterTestUtility {
  /*
   * @description Verify that all Go_Router__mdt records correctly instantiate.
   * @return String error message if a router failed to instantiate. Otherwise, null.
   */
  public static String verifyAllRouters() {
    Go_Router__mdt[] routers = [SELECT Key__c FROM Go_Router__mdt];

    for (Go_Router__mdt router : routers) {
      try {
        GoRouter.forKey(router.Key__c);
      } catch (Exception e) {
        return 'Go_Router__mdt with key "' +
          router.Key__c +
          '" failed to instantiate for reason: ' +
          e.getMessage();
      }
    }

    return null;
  }

  private GoRouterTestUtility() {
  }
}