go-router/main/default/objects/Go_Router__mdt/Go_Router__mdt.object-meta.xml
<CustomObject>
    <description>Definitions of all routes exposed to the /apex/go endpoint.</description>
    <label>Go Router</label>
    <pluralLabel>Go Routers</pluralLabel>
</CustomObject>

go-router/main/default/objects/Go_Router__mdt/fields/Redirect_Path__c.field-meta.xml
<CustomField>
    <fullName>Redirect_Path__c</fullName>
    <description>The URL path the user will be redirected to.</description>
    <inlineHelpText>The URL path the user will be redirected to.</inlineHelpText>
    <label>Redirect Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

go-router/main/default/objects/Go_Router__mdt/fields/Redirect_Path_With_Param__c.field-meta.xml
<CustomField>
    <fullName>Redirect_Path_With_Param__c</fullName>
    <description>Specifies a different redirect path if a non-empty parameter is passed to the router. Use {0} in the route to inject the parameter.</description>
    <inlineHelpText>Specifies a different redirect path if a non-empty parameter is passed to the router. Use {0} in the route to inject the parameter.</inlineHelpText>
    <label>Redirect Path With Param</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

go-router/main/default/objects/Go_Router__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>
        The type of router:
        - Redirect: Redirects to an internal Salesforce page
        - Record: Searches for a particular Salesforce record using a passed in parameter and query
        - Apex: Utilizes a custom Apex class to perform routing based on a passed in parameter
    </description>
    <inlineHelpText>
        The type of router:
        - Redirect: Redirects to an internal Salesforce page
        - Record: Searches for a particular Salesforce record using a passed in parameter and query
        - Apex: Utilizes a custom Apex class to perform routing based on a passed in parameter
    </inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Redirect</fullName>
                <default>true</default>
                <label>Redirect</label>
            </value>
            <value>
                <fullName>Record</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

go-router/main/default/classes/GoRouterRedirectTest.cls
/**
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @group GoRouter
 * @description Test Class for GoRouterRedirect.
 */
@IsTest(isParallel=true)
private without sharing class GoRouterRedirectTest {
  private static final String PATH = '/path/';
  private static final String PATH_WITH_PARAM = '/path/{0}';
  private static final String INPUT = 'input';

  private static GoRouter router = GoRouter.createInstanceOf(
    new Go_Router__mdt(
      Type__c = 'Redirect',
      Redirect_Path__c = PATH,
      Redirect_Path_With_Param__c = PATH_WITH_PARAM
    )
  );

  /*
   * @description A redirect specifying no param succeeds.
   */
  @IsTest
  private static void redirectNoParamShouldSucceed() {
    String result = router.route(null);

    System.assertEquals(PATH, result, 'Expected to route to configured path');
  }

  /*
   * @description A redirect specifying a param succeeds.
   */
  @IsTest
  private static void redirectParamShouldSucceed() {
    String result = router.route(INPUT);

    System.assertEquals(
      PATH + INPUT,
      result,
      'Expected to route to path with injected parameter'
    );
  }

  /*
   * @description A redirect specifying a param but without a param route succeeds
   */
  @IsTest
  private static void redirectParamButNoParamRouteShouldSucceed() {
    ROUTER.config.Redirect_Path_With_Param__c = null;

    String result = router.route(INPUT);

    System.assertEquals(
      PATH,
      result,
      'Expected to route to default path since no param path exists.'
    );
  }
}