go-router/main/default/objects/Go_Router__mdt/Go_Router__mdt.object-meta.xml
<CustomObject>
    <description>Definitions of all routes exposed to the /apex/go endpoint.</description>
    <label>Go Router</label>
    <pluralLabel>Go Routers</pluralLabel>
</CustomObject>

go-router/main/default/objects/Go_Router__mdt/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <description>Apex: Specifies the Apex class to invoke for routing. The class must implement GoRouter, and its route(String param) method will be invoked on routing.</description>
    <inlineHelpText>Apex: Specifies the Apex class to invoke for routing. The class must implement GoRouter, and its route(String param) method will be invoked on routing.</inlineHelpText>
    <label>Apex Class</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

go-router/main/default/objects/Go_Router__mdt/fields/Custom_Permission__c.field-meta.xml
<CustomField>
    <fullName>Custom_Permission__c</fullName>
    <description>DeveloperName of a CustomPermission. If specified, the user must have this custom permission to view/use this router.</description>
    <inlineHelpText>DeveloperName of a CustomPermission. If specified, the user must have this custom permission to view/use this router.</inlineHelpText>
    <label>Custom Permission</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

go-router/main/default/objects/Go_Router__mdt/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>The SObject Type being searched for.</description>
    <inlineHelpText>The SObject Type being searched for.</inlineHelpText>
    <label>Entity</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

go-router/main/default/objects/Go_Router__mdt/fields/Input__c.field-meta.xml
<CustomField>
    <fullName>Input__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <description>Used for documentation in the help page. Describe the expected input parameter to send to the Router.</description>
    <inlineHelpText>Used for documentation in the help page. Describe the expected input parameter to send to the Router.</inlineHelpText>
    <label>Input</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

go-router/main/default/objects/Go_Router__mdt/fields/Is_Default_Router__c.field-meta.xml
<CustomField>
    <fullName>Is_Default_Router__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Specifies if this router should be utilized if no explicit route is provided. Only one router should have a value of true.</description>
    <inlineHelpText>Specifies if this router should be utilized if no explicit route is provided. Only one router should have a value of true.</inlineHelpText>
    <label>Is Default Router?</label>
    <type>Checkbox</type>
</CustomField>

go-router/main/default/objects/Go_Router__mdt/fields/Is_Setup_Record__c.field-meta.xml
<CustomField>
    <fullName>Is_Setup_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Specifies if the record is a type found within the Setup menu. Used for redirecting to the proper page.</description>
    <inlineHelpText>Specifies if the record is a type found within the Setup menu. Used for redirecting to the proper page.</inlineHelpText>
    <label>Is Setup Record?</label>
    <type>Checkbox</type>
</CustomField>

go-router/main/default/objects/Go_Router__mdt/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>The route exposed for this GoRouter (i.e. /apex/go/key =&gt; activates this router).</description>
    <inlineHelpText>The route exposed for this GoRouter (i.e. /apex/go/key =&gt; activates this router).</inlineHelpText>
    <label>Key</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

go-router/main/default/objects/Go_Router__mdt/fields/Like_Query__c.field-meta.xml
<CustomField>
    <fullName>Like_Query__c</fullName>
    <description>
        The fallback query used to lookup the record with a LIKE wildcard. Available binding variables:
        - :likeParam (%param%)
        - :startsQuery (param%)
        - :endsQuery (%param)
    </description>
    <inlineHelpText>
        The fallback query used to lookup the record with a LIKE wildcard. Available binding variables:
        - :likeParam (%param%)
        - :startsQuery (param%)
        - :endsQuery (%param)
    </inlineHelpText>
    <label>Like Query</label>
    <type>TextArea</type>
</CustomField>

go-router/main/default/objects/Go_Router__mdt/fields/Query__c.field-meta.xml
<CustomField>
    <fullName>Query__c</fullName>
    <description>
        The WHERE clause of a SOQL query used to find the record:
        - Use :param to pass in the String input
        - Use :paramAsNumber to pass in the input cast as a Double
    </description>
    <inlineHelpText>
        The WHERE clause of a SOQL query used to find the record:
        - Use :param to pass in the String input
        - Use :paramAsNumber to pass in the input cast as a Double
    </inlineHelpText>
    <label>Query</label>
    <type>TextArea</type>
</CustomField>

go-router/main/default/objects/Go_Router__mdt/fields/Record_Page__c.field-meta.xml
<CustomField>
    <fullName>Record_Page__c</fullName>
    <description>Overwrites the default record page to route the located record. Use &quot;{0}&quot; in the specified URL to inject the Id of the record into the URL. The default record page if left blank is: /{0}</description>
    <inlineHelpText>Overwrites the default record page to route the located record. Use &quot;{0}&quot; in the specified URL to inject the Id of the record into the URL. The default record page if left blank is: /{0}</inlineHelpText>
    <label>Record Page</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

go-router/main/default/objects/Go_Router__mdt/fields/Redirect_Path__c.field-meta.xml
<CustomField>
    <fullName>Redirect_Path__c</fullName>
    <description>The URL path the user will be redirected to.</description>
    <inlineHelpText>The URL path the user will be redirected to.</inlineHelpText>
    <label>Redirect Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

go-router/main/default/objects/Go_Router__mdt/fields/Redirect_Path_With_Param__c.field-meta.xml
<CustomField>
    <fullName>Redirect_Path_With_Param__c</fullName>
    <description>Specifies a different redirect path if a non-empty parameter is passed to the router. Use {0} in the route to inject the parameter.</description>
    <inlineHelpText>Specifies a different redirect path if a non-empty parameter is passed to the router. Use {0} in the route to inject the parameter.</inlineHelpText>
    <label>Redirect Path With Param</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

go-router/main/default/objects/Go_Router__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>
        The type of router:
        - Redirect: Redirects to an internal Salesforce page
        - Record: Searches for a particular Salesforce record using a passed in parameter and query
        - Apex: Utilizes a custom Apex class to perform routing based on a passed in parameter
    </description>
    <inlineHelpText>
        The type of router:
        - Redirect: Redirects to an internal Salesforce page
        - Record: Searches for a particular Salesforce record using a passed in parameter and query
        - Apex: Utilizes a custom Apex class to perform routing based on a passed in parameter
    </inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Redirect</fullName>
                <default>true</default>
                <label>Redirect</label>
            </value>
            <value>
                <fullName>Record</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

go-router/main/default/objects/Go_Router__mdt/fields/Usage__c.field-meta.xml
<CustomField>
    <fullName>Usage__c</fullName>
    <description>Used for documentation in the help page. Provide a brief explanation of how to use this router</description>
    <inlineHelpText>Used for documentation in the help page. Provide a brief explanation of how to use this router</inlineHelpText>
    <label>Usage</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

go-router/main/default/classes/GoRouter.cls
/**
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @group GoRouter
 * @description Base definition of a GoRouter. Contains Utiltiy methods for
 * loading implementations.
 */
public with sharing abstract class GoRouter {
  /*
   * @description Static constants storing the different type of GoRouters.
   */
  @TestVisible
  private static final String GOROUTER_TYPE_REDIRECT = 'Redirect';
  @TestVisible
  private static final String GOROUTER_TYPE_RECORD = 'Record';
  @TestVisible
  private static final String GOROUTER_TYPE_APEX = 'Apex';

  /*
   * @description private subclass for query operations. Can be overridden for
   * unit tests.
   */
  @TestVisible
  private static GoRouter.Selector configSelector = new GoRouter.Selector();

  /*
   * @description The routing rules defined for this router.
   */
  @TestVisible
  public final Go_Router__mdt config;

  /*
   * @description Boolean indicating if the router matched based on the input.
   */
  public boolean matchedOnInput = false;

  /*
   * @description Initializer used for native GoRouter implementations (Redirect
   * & Record).
   */
  public GoRouter(Go_Router__mdt config) {
    this.config = config;
  }

  /*
   * @description Initialized used for Apex GoRouter extension implementations.
   */
  public GoRouter() {
  }

  /*
   * @description Abstract method all GoRouters implement to define routing
   * rules based on input provided.
   * @param param - String input used for routing to a path.
   * @return String relative URL path to redirect to.
   */
  public abstract String route(String param);

  /*
   * @description Helper method to delegate routing work to another router.
   * The outcome of this router's matchedOnInput is updated based on the result of the delegate.
   * @param param - String input passed to delegate router.
   * @param router - Delegate GoRouter to which query is passed to.
   * @return String result of router.
   */
  protected String delegateTo(String param, GoRouter router) {
    return delegateTo(param, new List<GoRouter>{ router });
  }

  /*
   * @description Helper method to delegate routing work to list of other routers.
   * The first router that successfully matchedOnInput will return its result.
   * If no router matches on the input, then no result is returned.
   * The outcome of this router's matchedOnInput is updated based on the result of the delegates.
   * @param param - String input passed to delegate router.
   * @param routers - Delegate GoRouters to which query is passed to.
   * @return String result of first successful router.
   */
  protected String delegateTo(String param, GoRouter[] routers) {
    for (GoRouter router : routers) {
      String result = router?.route(param);
      if (router?.matchedOnInput == true) {
        matchedOnInput = true;
        return result;
      }
    }
    matchedOnInput = false;
    return '';
  }

  /*
   * @description Helper method to fetch Go_Router__mdt and create the
   * associated GoRouter implementation defined by the metadata.
   * @param key - String mapping to a specific Go_Router__mdt key.
   * @return GoRouter class instantiation matching key.
   */
  public static GoRouter forKey(String key) {
    GoRouter[] routers = GoRouter.forKeys(new Set<String>{ key });
    return routers.isEmpty() ? null : routers[0];
  }

  /*
   * @description Helper method to fetch Go_Router__mdt and create the
   * associated GoRouter implementation defined by the metadata.
   * @param keys - Set<String> mapping to specific Go_Router__mdt keys.
   * @return GoRouter[] list of implementations matching key.
   */
  public static GoRouter[] forKeys(Set<String> keys) {
    Go_Router__mdt[] configs = configSelector.getRoutersWithKeys(keys);

    List<GoRouter> routers = new List<GoRouter>();
    for (Go_Router__mdt config : configs) {
      GoRouter router = createInstanceOf(config);
      if (router != null) {
        routers.add(router);
      }
    }
    return routers;
  }

  /*
   * @description Instantiate a GoRouter based on the router configuration.
   * Will return null if the user does not have the associated custom permission.
   * @param router - Go_Router__mdt defining the Router configuration.
   * @returns GoRouter instance of that class.
   */
  @TestVisible
  private static GoRouter createInstanceOf(Go_Router__mdt router) {
    if (
      !String.isBlank(router.Custom_Permission__c) &&
      !configSelector.hasCustomPermission(router.Custom_Permission__c)
    ) {
      return null;
    }
    if (router.Type__c == GOROUTER_TYPE_REDIRECT) {
      return new GoRouterRedirect(router);
    }
    if (router.Type__c == GOROUTER_TYPE_RECORD) {
      return new GoRouterRecord(router);
    }
    if (router.Type__c == GOROUTER_TYPE_APEX) {
      return GoRouter.createInstanceOf(router.Apex_Class__c);
    }
    return null;
  }

  /*
   * @description Uses Apex Reflection to create a GoRouter instance from a
   * class name. Will fail if the passed class name does not conform to GoRouter.
   * @param routerClass - String name of Apex class.
   * @returns GoRouter instance of that class.
   */
  private static GoRouter createInstanceOf(String routerClass) {
    Type t = Type.forName(routerClass);
    if (t == null || !GoRouter.class.isAssignableFrom(t)) {
      throw new GoRoutingException('Invalid Apex Class: ' + routerClass);
    }
    return (GoRouter) t.newInstance();
  }

  public class GoRoutingException extends Exception {
  }

  /*
   * @description private subclass for query operations. Can be overridden for
   * unit tests.
   */
  @TestVisible
  private without sharing virtual class Selector {
    Map<String, Boolean> permissionMap = new Map<String, Boolean>();

    public virtual boolean hasCustomPermission(String permission) {
      if (!permissionMap.containsKey(permission)) {
        Boolean hasPermission = FeatureManagement.checkPermission(permission);
        permissionMap.put(permission, hasPermission);
      }
      return permissionMap.get(permission);
    }

    public virtual Go_Router__mdt[] getRoutersWithKeys(Set<String> keys) {
      return [
        SELECT
          Apex_Class__c,
          Custom_Permission__c,
          Entity__c,
          Input__c,
          Is_Default_Router__c,
          Is_Setup_Record__c,
          Key__c,
          Record_Page__c,
          Redirect_Path__c,
          Redirect_Path_With_Param__c,
          Like_Query__c,
          Query__c,
          Type__c,
          Usage__c
        FROM Go_Router__mdt
        WHERE Key__c IN :keys
      ];
    }
  }
}