go-router/main/default/objects/Go_Router__mdt/Go_Router__mdt.object-meta.xml
<CustomObject>
    <description>Definitions of all routes exposed to the /apex/go endpoint.</description>
    <label>Go Router</label>
    <pluralLabel>Go Routers</pluralLabel>
</CustomObject>

go-router/main/default/objects/Go_Router__mdt/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>The SObject Type being searched for.</description>
    <inlineHelpText>The SObject Type being searched for.</inlineHelpText>
    <label>Entity</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

go-router/main/default/objects/Go_Router__mdt/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>The route exposed for this GoRouter (i.e. /apex/go/key =&gt; activates this router).</description>
    <inlineHelpText>The route exposed for this GoRouter (i.e. /apex/go/key =&gt; activates this router).</inlineHelpText>
    <label>Key</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

go-router/main/default/objects/Go_Router__mdt/fields/Like_Query__c.field-meta.xml
<CustomField>
    <fullName>Like_Query__c</fullName>
    <description>
        The fallback query used to lookup the record with a LIKE wildcard. Available binding variables:
        - :likeParam (%param%)
        - :startsQuery (param%)
        - :endsQuery (%param)
    </description>
    <inlineHelpText>
        The fallback query used to lookup the record with a LIKE wildcard. Available binding variables:
        - :likeParam (%param%)
        - :startsQuery (param%)
        - :endsQuery (%param)
    </inlineHelpText>
    <label>Like Query</label>
    <type>TextArea</type>
</CustomField>

go-router/main/default/objects/Go_Router__mdt/fields/Query__c.field-meta.xml
<CustomField>
    <fullName>Query__c</fullName>
    <description>
        The WHERE clause of a SOQL query used to find the record:
        - Use :param to pass in the String input
        - Use :paramAsNumber to pass in the input cast as a Double
    </description>
    <inlineHelpText>
        The WHERE clause of a SOQL query used to find the record:
        - Use :param to pass in the String input
        - Use :paramAsNumber to pass in the input cast as a Double
    </inlineHelpText>
    <label>Query</label>
    <type>TextArea</type>
</CustomField>

go-router/main/default/objects/Go_Router__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>
        The type of router:
        - Redirect: Redirects to an internal Salesforce page
        - Record: Searches for a particular Salesforce record using a passed in parameter and query
        - Apex: Utilizes a custom Apex class to perform routing based on a passed in parameter
    </description>
    <inlineHelpText>
        The type of router:
        - Redirect: Redirects to an internal Salesforce page
        - Record: Searches for a particular Salesforce record using a passed in parameter and query
        - Apex: Utilizes a custom Apex class to perform routing based on a passed in parameter
    </inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Redirect</fullName>
                <default>true</default>
                <label>Redirect</label>
            </value>
            <value>
                <fullName>Record</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

go-router/main/default/objects/Go_Router_Log__c/Go_Router_Log__c.object-meta.xml
<CustomObject>
    <description>Usage Log for Go Router tool.</description>
    <label>Go Router Log</label>
    <nameField>
        <displayFormat>GR-{000000}</displayFormat>
        <label>Go Router Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Go Router Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

go-router/main/default/objects/Go_Router_Log__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>The Key value passed into the Go Router request</description>
    <label>Key</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

go-router/main/default/classes/GoRouterRecordTest.cls
/**
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @group GoRouter
 * @description Test class for GoRouterRecord.
 */
@IsTest(isParallel=true)
private without sharing class GoRouterRecordTest {
  private static final String KEY = GoRouterRecordTest.class.toString();

  private static GoRouter router = GoRouter.createInstanceOf(
    new Go_Router__mdt(
      Type__c = 'Record',
      Entity__c = Go_Router_Log__c.class.toString(),
      Query__c = 'Key__c = :param',
      Like_Query__c = 'Key__c LIKE :likeParam'
    )
  );

  private static Go_Router_Log__c record {
    get {
      return [SELECT Id FROM Go_Router_Log__c WHERE Key__c = :KEY LIMIT 1];
    }
    set;
  }

  @TestSetup
  static void makeData() {
    insert new Go_Router_Log__c(Key__c = KEY);
  }

  /*
   * @description Using a query with an exact match succeeds.
   */
  @IsTest
  private static void standardObjectExactQueryShouldFindRecord() {
    String result = router.route(KEY);
    String recordId = String.valueOf(record.Id).substring(0, 15);

    System.assert(
      result.contains(recordId),
      'Expected router to route to record from standard query.'
    );
  }

  /*
   * @description Using a query with a LIKE query succeeds.
   */
  @IsTest
  private static void standardObjectLikeQueryShouldFindRecord() {
    String result = router.route(KEY.substring(0, 2));
    String recordId = String.valueOf(record.Id).substring(0, 15);

    System.assert(
      result.contains(recordId),
      'Expected router to route to record from LIKE query.'
    );
  }

  /*
   * @description Supplying no query routes to the Object's List View Page.
   */
  @IsTest
  private static void standardObjectNoInputShouldRouteToListView() {
    String result = router.route('');

    System.assert(
      result.contains(Go_Router_Log__c.class.toString()),
      'Expected router to route to Object List View with no input'
    );
  }

  /*
   * @description Supplying a query without an exact match routes to a scoped
   * search for the object.
   */
  @IsTest
  private static void standardObjectNoMatchOnInputShouldRouteToSearch() {
    String input = 'InputThatDoesNotMatch';

    String result = router.route(input);

    System.assert(
      result.contains('/one/one.app'),
      'Expected router to route to Search'
    );
    System.assertEquals(
      false,
      router.matchedOnInput,
      'Expected router to properly report missing on input.'
    );
  }
}