go-router/main/default/objects/Go_Router__mdt/Go_Router__mdt.object-meta.xml
<CustomObject>
    <description>Definitions of all routes exposed to the /apex/go endpoint.</description>
    <label>Go Router</label>
    <pluralLabel>Go Routers</pluralLabel>
</CustomObject>

go-router/main/default/objects/Go_Router__mdt/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <description>Apex: Specifies the Apex class to invoke for routing. The class must implement GoRouter, and its route(String param) method will be invoked on routing.</description>
    <inlineHelpText>Apex: Specifies the Apex class to invoke for routing. The class must implement GoRouter, and its route(String param) method will be invoked on routing.</inlineHelpText>
    <label>Apex Class</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

go-router/main/default/objects/Go_Router__mdt/fields/Input__c.field-meta.xml
<CustomField>
    <fullName>Input__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <description>Used for documentation in the help page. Describe the expected input parameter to send to the Router.</description>
    <inlineHelpText>Used for documentation in the help page. Describe the expected input parameter to send to the Router.</inlineHelpText>
    <label>Input</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

go-router/main/default/objects/Go_Router__mdt/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>The route exposed for this GoRouter (i.e. /apex/go/key =&gt; activates this router).</description>
    <inlineHelpText>The route exposed for this GoRouter (i.e. /apex/go/key =&gt; activates this router).</inlineHelpText>
    <label>Key</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

go-router/main/default/objects/Go_Router__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>
        The type of router:
        - Redirect: Redirects to an internal Salesforce page
        - Record: Searches for a particular Salesforce record using a passed in parameter and query
        - Apex: Utilizes a custom Apex class to perform routing based on a passed in parameter
    </description>
    <inlineHelpText>
        The type of router:
        - Redirect: Redirects to an internal Salesforce page
        - Record: Searches for a particular Salesforce record using a passed in parameter and query
        - Apex: Utilizes a custom Apex class to perform routing based on a passed in parameter
    </inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Redirect</fullName>
                <default>true</default>
                <label>Redirect</label>
            </value>
            <value>
                <fullName>Record</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

go-router/main/default/objects/Go_Router__mdt/fields/Usage__c.field-meta.xml
<CustomField>
    <fullName>Usage__c</fullName>
    <description>Used for documentation in the help page. Provide a brief explanation of how to use this router</description>
    <inlineHelpText>Used for documentation in the help page. Provide a brief explanation of how to use this router</inlineHelpText>
    <label>Usage</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

go-router/main/default/objects/Go_Router_Log__c/Go_Router_Log__c.object-meta.xml
<CustomObject>
    <description>Usage Log for Go Router tool.</description>
    <label>Go Router Log</label>
    <nameField>
        <displayFormat>GR-{000000}</displayFormat>
        <label>Go Router Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Go Router Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

go-router/main/default/objects/Go_Router_Log__c/fields/Input__c.field-meta.xml
<CustomField>
    <fullName>Input__c</fullName>
    <description>The Input passed into the Go Router request</description>
    <label>Input</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

go-router/main/default/objects/Go_Router_Log__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>The Key value passed into the Go Router request</description>
    <label>Key</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

go-router/main/default/objects/Go_Router_Log__c/fields/Matched_On_Input__c.field-meta.xml
<CustomField>
    <fullName>Matched_On_Input__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox determining if Go Router found a match based on input provided</description>
    <label>Matched On Input?</label>
    <type>Checkbox</type>
</CustomField>

go-router/main/default/classes/GoControllerTest.cls
/**
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @group GoRouter
 * @description Test class for GoController.
 */
@IsTest(isParallel=true)
private without sharing class GoControllerTest {
  private static GoController objectUnderTest = new GoController();

  private static Go_Router__mdt defaultRouter = null;
  private static Go_Router__mdt[] allRouters = new List<Go_Router__mdt>{};
  private static boolean hasDeveloperPermission = false;
  private static Go_Router_Log__c loggedResult = null;

  static {
    GoController.selector = new GoControllerTest.Selector();
    GoRouter.configSelector = new GoControllerTest.GoRouterSelector();
  }

  /**
   * @description Check that routers are properly converted and returned to VF page.
   */
  @IsTest
  private static void routesShouldFetchAndReturnSerializedRoutes() {
    Go_Router__mdt router = new Go_Router__mdt(
      Key__c = 'key',
      Input__c = 'input',
      Usage__c = 'usage'
    );
    allRouters.add(router);

    GoController.Route[] routes = objectUnderTest.routes;

    System.assertEquals(1, routes.size(), 'Expected to get one route');
    System.assertEquals(
      router.Key__c,
      routes[0].key,
      'Expected route to properly store the key'
    );
    System.assertEquals(
      router.Input__c,
      routes[0].input,
      'Expected route to properly store the input'
    );
    System.assertEquals(
      router.Usage__c,
      routes[0].usage,
      'Expected route to properly store the usage'
    );
  }

  /**
   * @description If the URL param is included, route straight to the value.
   */
  @IsTest
  private static void urlParamWithValidUrlShouldRouteToValue() {
    String key = 'url';
    String param = '/relative/url/';

    objectUnderTest.query = key + ' ' + param;
    String result = objectUnderTest.goInput().getUrl();

    System.assertEquals(param, result, 'Expected to route to param value');
    System.assertEquals(
      null,
      loggedResult,
      'No logging expected for a redirect'
    );
  }

  /**
   * @description If the URL param is invalid, reroute to help page.
   */
  @IsTest
  private static void urlParamWithInvalidUrlShouldRouteToHelpPage() {
    String key = 'url';
    String param = 'invalidRelativeUrl';

    objectUnderTest.query = key + ' ' + param;
    String result = objectUnderTest.goInput().getUrl();

    System.assertEquals(
      GoController.TAB_URL,
      result,
      'Expected to route to tab help page'
    );
    System.assertEquals(
      null,
      loggedResult,
      'No logging expected for a redirect'
    );
  }

  /**
   * @description If no param is included, route to the help page.
   */
  @IsTest
  private static void emptyParamShouldRouteToHelpPage() {
    String result = objectUnderTest.route(new Map<String, String>());

    System.assertEquals(
      GoController.TAB_URL,
      result,
      'Expected to route to tab help page'
    );
    System.assertEquals(
      null,
      loggedResult,
      'No logging expected for a redirect'
    );
  }

  /**
   * @description If no param is included, route to the help page.
   */
  @IsTest
  private static void emptyParamAfterSanitizingShouldRouteToHelpPage() {
    String result = objectUnderTest.route('/++  ++/');

    System.assertEquals(
      GoController.TAB_URL,
      result,
      'Expected to route to tab help page'
    );
    System.assertEquals(
      null,
      loggedResult,
      'No logging expected for a redirect'
    );
  }

  /**
   * @description If the help param is included, route to the help page.
   */
  @IsTest
  private static void helpParamShouldRouteToHelpPage() {
    String key = 'help';

    String result = objectUnderTest.route(key);

    System.assertEquals(
      GoController.TAB_URL,
      result,
      'Expected to route to tab help page'
    );
    System.assertEquals(
      null,
      loggedResult,
      'No logging expected for a redirect'
    );
  }

  /**
   * @description If the tab param is included, route to nothing, rendering the VF page.
   */
  @IsTest
  private static void tabParamShouldRouteToNothing() {
    String key = GoController.TAB_PARAM;

    String result = objectUnderTest.route(key);

    System.assertEquals(null, result, 'Expected to route to nothing');
    System.assertEquals(
      'help',
      loggedResult.Key__c,
      'Expected "help" usage to be logged'
    );
  }

  /**
   * @description If an SF ID is passed as the query, it should route straight to the record page.
   */
  @IsTest
  private static void routingSFDCIdShouldRouteToPage() {
    Id recordId = '005000000000001';

    String result = objectUnderTest.route(String.valueOf(recordId));

    System.assertEquals(
      '/' + recordId,
      result,
      'Expected SFDC Id to auto route to record page'
    );
    System.assertEquals(
      'id',
      loggedResult.Key__c,
      'Expected "id" usage to be logged'
    );
  }

  /**
   * @description Test that the raw query param recursively reads the query.
   */
  @IsTest
  private static void rawQueryShouldBeProperlyDeconstructed() {
    String input = 'query query query query help';

    String result = objectUnderTest.route(input);

    System.assertEquals(
      GoController.TAB_URL,
      result,
      'Expected to route to tab help page after deconstructing raw query'
    );
    System.assertEquals(
      null,
      loggedResult,
      'No logging expected for a redirect'
    );
  }

  /**
   * @description Test that query matching a router definition properly routes.
   */
  @IsTest
  private static void keyMatchingRouterShouldProperlyRoute() {
    String key = 'mock';
    String param = 'value';
    allRouters.add(
      new Go_Router__mdt(
        Type__c = 'Apex',
        Apex_Class__c = 'GoControllerTest.MockRouter'
      )
    );

    String result = objectUnderTest.route(key + ' ' + param);

    System.assertEquals(param, result, 'Expected mock router to return param');
    System.assertEquals(
      key,
      loggedResult.Key__c,
      'Logger should properly log key'
    );
    System.assertEquals(
      param,
      loggedResult.Input__c,
      'Logger should properly log param'
    );
    System.assertEquals(
      true,
      loggedResult.Matched_On_Input__c,
      'Logger should properly log result'
    );
  }

  /**
   * @description Test that falling back to the default router properly routes.
   */
  @IsTest
  private static void defaultRouterShouldProperlyRoute() {
    String input = 'inputForDefault';
    defaultRouter = new Go_Router__mdt(
      Type__c = 'Apex',
      Apex_Class__c = 'GoControllerTest.MockRouter'
    );

    String result = objectUnderTest.route(input);

    System.assertEquals(
      input.toLowerCase(),
      result,
      'Expected mock router to return input'
    );
    System.assertEquals(
      'default',
      loggedResult.Key__c,
      'Logger should properly log use of default router'
    );
    System.assertEquals(
      input.toLowerCase(),
      loggedResult.Input__c,
      'Logger should properly log param'
    );
    System.assertEquals(
      true,
      loggedResult.Matched_On_Input__c,
      'Logger should properly log result'
    );
  }

  /**
   * @description Test that no default router found routes to the help page.
   */
  @IsTest
  private static void noDefaultRouterShouldProperlyRouteToHelp() {
    String input = 'input matching no router';

    String result = objectUnderTest.route(input);

    System.assertEquals(
      GoController.TAB_URL,
      result,
      'Expected to route to tab help page after deconstructing raw query'
    );
    System.assertEquals(
      null,
      loggedResult,
      'No logging expected for a redirect'
    );
  }

  private with sharing class Selector extends GoController.Selector {
    public override Go_Router__mdt[] getAllRouters() {
      return allRouters;
    }

    public override Go_Router__mdt[] getDefaultRouter() {
      return defaultRouter == null
        ? new List<Go_Router__mdt>{}
        : new List<Go_Router__mdt>{ defaultRouter };
    }

    public override boolean hasCustomPermission(String permission) {
      return hasDeveloperPermission;
    }

    public override void insertLog(Go_Router_Log__c log) {
      loggedResult = log;
    }
  }

  private with sharing class GoRouterSelector extends GoRouter.Selector {
    Integer calls = 0;
    public override Go_Router__mdt[] getRoutersWithKeys(Set<String> keys) {
      calls += 1;
      if (calls == 1) {
        return allRouters;
      } else {
        return GoController.selector.getDefaultRouter();
      }
    }
  }

  public without sharing class MockRouter extends GoRouter {
    public override String route(String param) {
      super.matchedOnInput = true;
      return param;
    }
  }
}